import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./GlobalRedux/provider";
import Header from "@/components/Header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ backgroundColor: "rgb(7, 15, 43)" }} className="w-full p-4 flex items-center justify-center">
          <Header></Header>
        </div>
        <ReduxProvider>{children} </ReduxProvider>
      </body>
    </html>
  );
}
